/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.javaguiproject;

/**
 *
 * @author Mdspa
 */
public class AdvancedSpeciesForm extends javax.swing.JFrame {

    /**
     * Creates new form AdvancedSpeciesForm
     */
    AMETForm form;
    public AdvancedSpeciesForm(AMETForm form) {
        this.form = form;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        advancedSpeciesSettingsLabel = new javax.swing.JLabel();
        speciesQueryInfoLabel = new javax.swing.JTextArea();
        manualInfoLabel = new javax.swing.JTextArea();
        manualTextField = new javax.swing.JTextField();
        manualSpeciesTextField = new javax.swing.JTextField();
        customSpeciesNameTextField = new javax.swing.JTextField();
        customSpeciesUnitTextField = new javax.swing.JTextField();
        customSpeciesNameLabel = new javax.swing.JLabel();
        customSpeciesUnitLabel = new javax.swing.JLabel();
        saveBurtton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        advancedSpeciesSettingsLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        advancedSpeciesSettingsLabel.setText("Advanced Species Settings");

        speciesQueryInfoLabel.setColumns(20);
        speciesQueryInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        speciesQueryInfoLabel.setLineWrap(true);
        speciesQueryInfoLabel.setRows(5);
        speciesQueryInfoLabel.setText("Enter a species query. Unlike above, this must be a properly formatted MySQL query string. This option is intended for advanced users. Example of a custom query is (2*d.Ca_ob+d.K_ob+2*d.Mg_ob+d.NA_ob) as NVC_ob, (2*d.Ca_mod+d.K_mod+2*d.Mg_mod+d.Na_mod) as NVC_mod. ");
        speciesQueryInfoLabel.setWrapStyleWord(true);
        speciesQueryInfoLabel.setOpaque(false);

        manualInfoLabel.setColumns(20);
        manualInfoLabel.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        manualInfoLabel.setLineWrap(true);
        manualInfoLabel.setRows(5);
        manualInfoLabel.setText("Enter a species (or multiple species) manually. Multiple species currently only applies to Soccer Goal plot and multi-species time series plot. Acceptable format is comma separated list of species (e.g. SO4,NO3,NH4). Names must match the names used in the AMET database. A mapping of the AMET database names can be found above.");
        manualInfoLabel.setWrapStyleWord(true);
        manualInfoLabel.setOpaque(false);

        customSpeciesNameLabel.setText("Enter a name for your custom species.");

        customSpeciesUnitLabel.setText("Enter the units for your sutom species. ");

        saveBurtton.setText("Save");

        cancelButton.setText("Cancel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(advancedSpeciesSettingsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speciesQueryInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manualInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manualTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manualSpeciesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customSpeciesUnitLabel)
                    .addComponent(customSpeciesNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customSpeciesNameLabel)
                    .addComponent(customSpeciesUnitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saveBurtton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(advancedSpeciesSettingsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manualInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manualTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(speciesQueryInfoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manualSpeciesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customSpeciesNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customSpeciesNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customSpeciesUnitLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customSpeciesUnitTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBurtton)
                    .addComponent(cancelButton))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advancedSpeciesSettingsLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel customSpeciesNameLabel;
    private javax.swing.JTextField customSpeciesNameTextField;
    private javax.swing.JLabel customSpeciesUnitLabel;
    private javax.swing.JTextField customSpeciesUnitTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea manualInfoLabel;
    private javax.swing.JTextField manualSpeciesTextField;
    private javax.swing.JTextField manualTextField;
    private javax.swing.JButton saveBurtton;
    private javax.swing.JTextArea speciesQueryInfoLabel;
    // End of variables declaration//GEN-END:variables
}
