/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.javaguiproject;

/**
 *
 * @author Mdspa
 */
public class ScatterPlotOptionsForm extends javax.swing.JFrame {

    /**
     * Creates new form ScatterPlotOptionsForm
     */
    AMETForm form;
    public ScatterPlotOptionsForm(AMETForm form) {
        this.form = form;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        plotOptionsPanel = new javax.swing.JPanel();
        confidenceLinesCheckBox = new javax.swing.JCheckBox();
        pcaRegionsCheckBox = new javax.swing.JCheckBox();
        modelValuesCheckBox = new javax.swing.JCheckBox();
        errorCheckBox = new javax.swing.JCheckBox();
        trendLineCheckBox = new javax.swing.JCheckBox();
        statisticsPanel = new javax.swing.JPanel();
        numberOfPairsCheckBox = new javax.swing.JCheckBox();
        meanObsCheckBox = new javax.swing.JCheckBox();
        meanModelCheckBox = new javax.swing.JCheckBox();
        indexOfAgreementCheckBox = new javax.swing.JCheckBox();
        correlationCheckBox = new javax.swing.JCheckBox();
        rSquaredCheckBox = new javax.swing.JCheckBox();
        rmseCheckBox = new javax.swing.JCheckBox();
        systematicRMSECheckBox = new javax.swing.JCheckBox();
        unsysematicRMSECheckBox = new javax.swing.JCheckBox();
        normMeanBiasCheckBox = new javax.swing.JCheckBox();
        normMeanErrorCheckBox = new javax.swing.JCheckBox();
        normMedianBiasCheckBox = new javax.swing.JCheckBox();
        normMedianErrorCheckBox = new javax.swing.JCheckBox();
        meanBiasCheckBox = new javax.swing.JCheckBox();
        meanErrorCheckBox = new javax.swing.JCheckBox();
        medianBiasCheckBox = new javax.swing.JCheckBox();
        medianErrorCheckBox = new javax.swing.JCheckBox();
        fractionalBiasCheckBox = new javax.swing.JCheckBox();
        fractionalErrorCheckBox = new javax.swing.JCheckBox();
        statisticsLabel = new javax.swing.JLabel();
        scatterPlotOptionsLabel = new javax.swing.JLabel();
        plotColorPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        color1Label = new javax.swing.JLabel();
        colorComboBox1 = new javax.swing.JComboBox<>();
        colorComboBox2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        color2Label = new javax.swing.JLabel();
        colorComboBox3 = new javax.swing.JComboBox<>();
        colorComboBox4 = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        color3Label = new javax.swing.JLabel();
        colorComboBox5 = new javax.swing.JComboBox<>();
        colorComboBox6 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        color4Label = new javax.swing.JLabel();
        colorComboBox7 = new javax.swing.JComboBox<>();
        colorComboBox8 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        color5Label = new javax.swing.JLabel();
        colorComboBox9 = new javax.swing.JComboBox<>();
        colorComboBox10 = new javax.swing.JComboBox<>();
        color6Label = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        colorComboBox11 = new javax.swing.JComboBox<>();
        colorComboBox12 = new javax.swing.JComboBox<>();
        color7Label = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        colorComboBox13 = new javax.swing.JComboBox<>();
        colorComboBox14 = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        color8Label = new javax.swing.JLabel();
        colorComboBox15 = new javax.swing.JComboBox<>();
        colorComboBox16 = new javax.swing.JComboBox<>();
        plotColorLabel = new javax.swing.JLabel();
        plotSymbolsLabel = new javax.swing.JLabel();
        plotSymbolpanel = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        network1Label = new javax.swing.JLabel();
        symbolComboBox1 = new javax.swing.JComboBox<>();
        jPanel15 = new javax.swing.JPanel();
        network2Label = new javax.swing.JLabel();
        symbolComboBox2 = new javax.swing.JComboBox<>();
        jPanel16 = new javax.swing.JPanel();
        network3Label = new javax.swing.JLabel();
        symbolComboBox3 = new javax.swing.JComboBox<>();
        jPanel17 = new javax.swing.JPanel();
        network4Label = new javax.swing.JLabel();
        symbolComboBox4 = new javax.swing.JComboBox<>();
        jPanel18 = new javax.swing.JPanel();
        network5Label = new javax.swing.JLabel();
        symbolComboBox5 = new javax.swing.JComboBox<>();
        jPanel19 = new javax.swing.JPanel();
        network6Label = new javax.swing.JLabel();
        symbolComboBox6 = new javax.swing.JComboBox<>();
        jPanel20 = new javax.swing.JPanel();
        network7Label = new javax.swing.JLabel();
        symbolComboBox7 = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        averageStatsCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        confidenceLinesCheckBox.setText(" Include 2-to-1 Confidence Lines ");

        pcaRegionsCheckBox.setText(" Use PCA Regions ");

        modelValuesCheckBox.setText(" Bin by Model Values (binned bias plot only) ");

        errorCheckBox.setText(" Include error on interactive binned plot ");

        trendLineCheckBox.setSelected(true);
        trendLineCheckBox.setText(" Include trend line on ggplot scatter plot ");

        javax.swing.GroupLayout plotOptionsPanelLayout = new javax.swing.GroupLayout(plotOptionsPanel);
        plotOptionsPanel.setLayout(plotOptionsPanelLayout);
        plotOptionsPanelLayout.setHorizontalGroup(
            plotOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plotOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plotOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confidenceLinesCheckBox)
                    .addComponent(pcaRegionsCheckBox)
                    .addComponent(modelValuesCheckBox)
                    .addComponent(errorCheckBox)
                    .addComponent(trendLineCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plotOptionsPanelLayout.setVerticalGroup(
            plotOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plotOptionsPanelLayout.createSequentialGroup()
                .addComponent(confidenceLinesCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pcaRegionsCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modelValuesCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trendLineCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        numberOfPairsCheckBox.setText("Number of Pairs ");

        meanObsCheckBox.setText("Mean Obs ");

        meanModelCheckBox.setText("Mean Model ");

        indexOfAgreementCheckBox.setSelected(true);
        indexOfAgreementCheckBox.setText("Index of Agreement ");

        correlationCheckBox.setText("Correlation");

        rSquaredCheckBox.setText("R Squared ");

        rmseCheckBox.setText("RMSE");

        systematicRMSECheckBox.setSelected(true);
        systematicRMSECheckBox.setText("Systematic RMSE");

        unsysematicRMSECheckBox.setSelected(true);
        unsysematicRMSECheckBox.setText("Unsystematic RMSE ");

        normMeanBiasCheckBox.setText(" Norm Mean Bias (NMB, %) ");

        normMeanErrorCheckBox.setText(" Norm Mean Error (NME, %) ");

        normMedianBiasCheckBox.setText(" Norm Median Bias (NMdnB, %) ");

        normMedianErrorCheckBox.setText(" Norm Median Error (NMdnE, %) ");

        meanBiasCheckBox.setText(" Mean Bias (MB) ");

        meanErrorCheckBox.setText(" Mean Error (ME) ");

        medianBiasCheckBox.setSelected(true);
        medianBiasCheckBox.setText(" Median Bias (MdnB) ");

        medianErrorCheckBox.setSelected(true);
        medianErrorCheckBox.setText(" Median Error (MdnE) ");

        fractionalBiasCheckBox.setText(" Fractional Bias (FB, %) ");

        fractionalErrorCheckBox.setText(" Fractional Error (FE, %) ");

        statisticsLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        statisticsLabel.setText("Statistics (Include up to 5)");

        javax.swing.GroupLayout statisticsPanelLayout = new javax.swing.GroupLayout(statisticsPanel);
        statisticsPanel.setLayout(statisticsPanelLayout);
        statisticsPanelLayout.setHorizontalGroup(
            statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticsPanelLayout.createSequentialGroup()
                .addGroup(statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numberOfPairsCheckBox)
                    .addComponent(meanObsCheckBox)
                    .addComponent(meanModelCheckBox)
                    .addComponent(indexOfAgreementCheckBox)
                    .addComponent(correlationCheckBox)
                    .addComponent(rSquaredCheckBox)
                    .addComponent(rmseCheckBox)
                    .addComponent(systematicRMSECheckBox)
                    .addComponent(unsysematicRMSECheckBox)
                    .addComponent(normMeanBiasCheckBox)
                    .addComponent(normMeanErrorCheckBox)
                    .addComponent(normMedianBiasCheckBox)
                    .addComponent(normMedianErrorCheckBox)
                    .addComponent(meanBiasCheckBox)
                    .addComponent(meanErrorCheckBox)
                    .addComponent(medianBiasCheckBox)
                    .addComponent(medianErrorCheckBox)
                    .addComponent(fractionalErrorCheckBox)
                    .addComponent(fractionalBiasCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statisticsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        statisticsPanelLayout.setVerticalGroup(
            statisticsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statisticsPanelLayout.createSequentialGroup()
                .addComponent(statisticsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberOfPairsCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meanObsCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meanModelCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indexOfAgreementCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correlationCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSquaredCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rmseCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(systematicRMSECheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(unsysematicRMSECheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(normMeanBiasCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(normMeanErrorCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(normMedianBiasCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(normMedianErrorCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meanBiasCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(meanErrorCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medianBiasCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medianErrorCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fractionalBiasCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fractionalErrorCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scatterPlotOptionsLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        scatterPlotOptionsLabel.setText("Scatter Plot Options");

        color1Label.setText("Color 1");

        colorComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Lgt Blue", "Drk Blue", "Red", "Lgt Red", "Yellow", "Drk Yellow", "Lgt Green", "Green", "Orange", "Brown", "Lgt Grey", "Med Grey", "Drk Grey", "Black", "Drk Green", "Purple", "None" }));
        colorComboBox1.setSelectedIndex(11);

        colorComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Lgt Blue", "Drk Blue", "Red", "Lgt Red", "Yellow", "Drk Yellow", "Lgt Green", "Green", "Orange", "Brown", "Lgt Grey", "Med Grey", "Drk Grey", "Black", "Drk Green", "Purple", "None" }));
        colorComboBox2.setSelectedIndex(11);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(color1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(color1Label)
                .addComponent(colorComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(colorComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        color2Label.setText("Color 2");

        colorComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Lgt Blue", "Drk Blue", "Red", "Lgt Red", "Yellow", "Drk Yellow", "Lgt Green", "Green", "Orange", "Brown", "Lgt Grey", "Med Grey", "Drk Grey", "Black", "Drk Green", "Purple", "None" }));
        colorComboBox3.setSelectedIndex(3);

        colorComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Lgt Blue", "Drk Blue", "Red", "Lgt Red", "Yellow", "Drk Yellow", "Lgt Green", "Green", "Orange", "Brown", "Lgt Grey", "Med Grey", "Drk Grey", "Black", "Drk Green", "Purple", "None" }));
        colorComboBox4.setSelectedIndex(3);

        color3Label.setText("Color 3");

        colorComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Lgt Blue", "Drk Blue", "Red", "Lgt Red", "Yellow", "Drk Yellow", "Lgt Green", "Green", "Orange", "Brown", "Lgt Grey", "Med Grey", "Drk Grey", "Black", "Drk Green", "Purple", "None" }));

        colorComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Lgt Blue", "Drk Blue", "Red", "Lgt Red", "Yellow", "Drk Yellow", "Lgt Green", "Green", "Orange", "Brown", "Lgt Grey", "Med Grey", "Drk Grey", "Black", "Drk Green", "Purple", "None" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(color3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(color3Label)
                .addComponent(colorComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(colorComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        color4Label.setText("Color 4");

        colorComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Lgt Blue", "Drk Blue", "Red", "Lgt Red", "Yellow", "Drk Yellow", "Lgt Green", "Green", "Orange", "Brown", "Lgt Grey", "Med Grey", "Drk Grey", "Black", "Drk Green", "Purple", "None" }));
        colorComboBox7.setSelectedIndex(15);

        colorComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Lgt Blue", "Drk Blue", "Red", "Lgt Red", "Yellow", "Drk Yellow", "Lgt Green", "Green", "Orange", "Brown", "Lgt Grey", "Med Grey", "Drk Grey", "Black", "Drk Green", "Purple", "None" }));
        colorComboBox8.setSelectedIndex(15);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(color4Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(color4Label)
                .addComponent(colorComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(colorComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        color5Label.setText("Color 5");

        colorComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Lgt Blue", "Drk Blue", "Red", "Lgt Red", "Yellow", "Drk Yellow", "Lgt Green", "Green", "Orange", "Brown", "Lgt Grey", "Med Grey", "Drk Grey", "Black", "Drk Green", "Purple", "None" }));
        colorComboBox9.setSelectedIndex(6);

        colorComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Lgt Blue", "Drk Blue", "Red", "Lgt Red", "Yellow", "Drk Yellow", "Lgt Green", "Green", "Orange", "Brown", "Lgt Grey", "Med Grey", "Drk Grey", "Black", "Drk Green", "Purple", "None" }));
        colorComboBox10.setSelectedIndex(6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(color5Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(color5Label)
                .addComponent(colorComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(colorComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel8.setText("Color 6");

        colorComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Lgt Blue", "Drk Blue", "Red", "Lgt Red", "Yellow", "Drk Yellow", "Lgt Green", "Green", "Orange", "Brown", "Lgt Grey", "Med Grey", "Drk Grey", "Black", "Drk Green", "Purple", "None" }));
        colorComboBox11.setSelectedIndex(9);

        colorComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Lgt Blue", "Drk Blue", "Red", "Lgt Red", "Yellow", "Drk Yellow", "Lgt Green", "Green", "Orange", "Brown", "Lgt Grey", "Med Grey", "Drk Grey", "Black", "Drk Green", "Purple", "None" }));
        colorComboBox12.setSelectedIndex(9);

        javax.swing.GroupLayout color6LabelLayout = new javax.swing.GroupLayout(color6Label);
        color6Label.setLayout(color6LabelLayout);
        color6LabelLayout.setHorizontalGroup(
            color6LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(color6LabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        color6LabelLayout.setVerticalGroup(
            color6LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(color6LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8)
                .addComponent(colorComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(colorComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel9.setText("Color 7");

        colorComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Lgt Blue", "Drk Blue", "Red", "Lgt Red", "Yellow", "Drk Yellow", "Lgt Green", "Green", "Orange", "Brown", "Lgt Grey", "Med Grey", "Drk Grey", "Black", "Drk Green", "Purple", "None" }));
        colorComboBox13.setSelectedIndex(10);

        colorComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Lgt Blue", "Drk Blue", "Red", "Lgt Red", "Yellow", "Drk Yellow", "Lgt Green", "Green", "Orange", "Brown", "Lgt Grey", "Med Grey", "Drk Grey", "Black", "Drk Green", "Purple", "None" }));
        colorComboBox14.setSelectedIndex(10);

        javax.swing.GroupLayout color7LabelLayout = new javax.swing.GroupLayout(color7Label);
        color7Label.setLayout(color7LabelLayout);
        color7LabelLayout.setHorizontalGroup(
            color7LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(color7LabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        color7LabelLayout.setVerticalGroup(
            color7LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(color7LabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(colorComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(colorComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        color8Label.setText("Color 8");

        colorComboBox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Lgt Blue", "Drk Blue", "Red", "Lgt Red", "Yellow", "Drk Yellow", "Lgt Green", "Green", "Orange", "Brown", "Lgt Grey", "Med Grey", "Drk Grey", "Black", "Drk Green", "Purple", "None" }));
        colorComboBox15.setSelectedIndex(16);

        colorComboBox16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blue", "Lgt Blue", "Drk Blue", "Red", "Lgt Red", "Yellow", "Drk Yellow", "Lgt Green", "Green", "Orange", "Brown", "Lgt Grey", "Med Grey", "Drk Grey", "Black", "Drk Green", "Purple", "None" }));
        colorComboBox16.setSelectedIndex(16);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(color8Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorComboBox16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(color8Label)
                    .addComponent(colorComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorComboBox16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(color2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(colorComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(color6Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(color7Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(color2Label)
                    .addComponent(colorComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(color6Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(color7Label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout plotColorPanelLayout = new javax.swing.GroupLayout(plotColorPanel);
        plotColorPanel.setLayout(plotColorPanelLayout);
        plotColorPanelLayout.setHorizontalGroup(
            plotColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plotColorPanelLayout.createSequentialGroup()
                .addGroup(plotColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        plotColorPanelLayout.setVerticalGroup(
            plotColorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plotColorPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        plotColorLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        plotColorLabel.setText("Plot Colors");

        plotSymbolsLabel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        plotSymbolsLabel.setText("Plot Symbols");

        network1Label.setText("Network 1");

        symbolComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Circle", "Triangle", "Square", "Diamond", "Star", "Burst", "X" }));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(network1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(symbolComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(network1Label)
                .addComponent(symbolComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        network2Label.setText("Network 2");

        symbolComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Triangle", "Circle", "Square", "Diamond", "Star", "Burst", "X" }));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(network2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(symbolComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(network2Label)
                .addComponent(symbolComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        network3Label.setText("Network 3");

        symbolComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Square", "Circle", "Triangle", "Diamond", "Star", "Burst", "X" }));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(network3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(symbolComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(network3Label)
                .addComponent(symbolComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        network4Label.setText("Network 4");

        symbolComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diamond", "Circle", "Triangle", "Square", "Star", "Burst", "X" }));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(network4Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(symbolComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(network4Label)
                .addComponent(symbolComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        network5Label.setText("Network 5");

        symbolComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Star", "Circle", "Triangle", "Square", "Diamond", "Burst", "X" }));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(network5Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(symbolComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(network5Label)
                .addComponent(symbolComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        network6Label.setText("Network 6");

        symbolComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Burst", "Circle", "Triangle", "Square", "Diamond", "Star", "X" }));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(network6Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(symbolComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(network6Label)
                .addComponent(symbolComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        network7Label.setText("Network 7");

        symbolComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X", "Circle", "Triangle", "Square", "Diamond", "Star", "Burst" }));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(network7Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(symbolComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(network7Label)
                .addComponent(symbolComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout plotSymbolpanelLayout = new javax.swing.GroupLayout(plotSymbolpanel);
        plotSymbolpanel.setLayout(plotSymbolpanelLayout);
        plotSymbolpanelLayout.setHorizontalGroup(
            plotSymbolpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plotSymbolpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(plotSymbolpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(plotSymbolpanelLayout.createSequentialGroup()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        plotSymbolpanelLayout.setVerticalGroup(
            plotSymbolpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plotSymbolpanelLayout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        averageStatsCheckBox.setText("Use averages for statistic calculations (scatter plots only)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plotOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scatterPlotOptionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(averageStatsCheckBox)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(plotColorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(plotColorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(plotSymbolsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(plotSymbolpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scatterPlotOptionsLabel)
                    .addComponent(plotColorLabel)
                    .addComponent(plotSymbolsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(plotOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(statisticsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(plotColorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(plotSymbolpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(averageStatsCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        form.conf_line = form.checkBoxFormat(confidenceLinesCheckBox);
        form.pca_flag = form.checkBoxFormat(pcaRegionsCheckBox);
        form.bin_by_mod = form.checkBoxFormat(modelValuesCheckBox);
        form.inc_error =  form.checkBoxFormat(errorCheckBox);
        form.trend_line = form.checkBoxFormat(trendLineCheckBox);
        form.stats_flags = statFlagFormat();
        form.plot_colors = plotColors1Format();
        form.plot_colors2 = plotColors2Format();
        form.plot_symbols = plotSymbolsFormat();
        form.use_avg_stats = form.checkBoxFormat(averageStatsCheckBox);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private String statFlagFormat() {
        String str = "c("
                + form.checkBoxFormat(numberOfPairsCheckBox) + ","
                + form.checkBoxFormat(meanObsCheckBox) + ","
                + form.checkBoxFormat(meanModelCheckBox) + ","
                + form.checkBoxFormat(indexOfAgreementCheckBox) + ","
                + form.checkBoxFormat(correlationCheckBox) + ","
                + form.checkBoxFormat(rSquaredCheckBox) + ","
                + form.checkBoxFormat(rmseCheckBox) + ","
                + form.checkBoxFormat(systematicRMSECheckBox) + ","
                + form.checkBoxFormat(unsysematicRMSECheckBox) + ","
                + form.checkBoxFormat(normMeanBiasCheckBox) + ","
                + form.checkBoxFormat(normMeanErrorCheckBox) + ","
                + form.checkBoxFormat(normMedianBiasCheckBox) + ","
                + form.checkBoxFormat(normMedianErrorCheckBox) + ","
                + form.checkBoxFormat(meanBiasCheckBox) + ","
                + form.checkBoxFormat(meanErrorCheckBox) + ","
                + form.checkBoxFormat(medianBiasCheckBox) + ","
                + form.checkBoxFormat(medianErrorCheckBox) + ","
                + form.checkBoxFormat(fractionalBiasCheckBox) + ","
                + form.checkBoxFormat(fractionalErrorCheckBox);
        return str + ")";
    }
    
    private String plotColors1Format() {
        String str = "c("
                + "\"" + colorFormat(colorComboBox1.getSelectedItem().toString()) + "\","
                + "\"" + colorFormat(colorComboBox3.getSelectedItem().toString()) + "\","
                + "\"" + colorFormat(colorComboBox5.getSelectedItem().toString()) + "\","
                + "\"" + colorFormat(colorComboBox7.getSelectedItem().toString()) + "\","
                + "\"" + colorFormat(colorComboBox9.getSelectedItem().toString()) + "\","
                + "\"" + colorFormat(colorComboBox11.getSelectedItem().toString()) + "\","
                + "\"" + colorFormat(colorComboBox13.getSelectedItem().toString()) + "\","
                + "\"" + colorFormat(colorComboBox15.getSelectedItem().toString()) + "\"";
        return str + ")";
    }
    private String plotColors2Format() {
        String str = "c("
                + "\"" + colorFormat(colorComboBox2.getSelectedItem().toString()) + "\","
                + "\"" + colorFormat(colorComboBox4.getSelectedItem().toString()) + "\","
                + "\"" + colorFormat(colorComboBox6.getSelectedItem().toString()) + "\","
                + "\"" + colorFormat(colorComboBox8.getSelectedItem().toString()) + "\","
                + "\"" + colorFormat(colorComboBox10.getSelectedItem().toString()) + "\","
                + "\"" + colorFormat(colorComboBox12.getSelectedItem().toString()) + "\","
                + "\"" + colorFormat(colorComboBox14.getSelectedItem().toString()) + "\","
                + "\"" + colorFormat(colorComboBox16.getSelectedItem().toString()) + "\"";
        return str + ")";
    }
    private String plotSymbolsFormat() {
        String str = "c("
                + symbolFormat(symbolComboBox1.getSelectedItem().toString()) + ","
                + symbolFormat(symbolComboBox2.getSelectedItem().toString()) + ","
                + symbolFormat(symbolComboBox3.getSelectedItem().toString()) + ","
                + symbolFormat(symbolComboBox4.getSelectedItem().toString()) + ","
                + symbolFormat(symbolComboBox5.getSelectedItem().toString()) + ","
                + symbolFormat(symbolComboBox6.getSelectedItem().toString()) + ","
                + symbolFormat(symbolComboBox7.getSelectedItem().toString());
        return str + ")";
    }
    
    private String colorFormat(String str) {
        String color = "";
        switch(str) {
            case "Blue":
                color = "blue";
                break;
            case "Lgt Blue":
                color = "skyblue2";
                break;
            case "Drk Blue":
                color = "darkblue";
                break;
            case "Red":
                color = "red";
                break;
            case "Lgt Red":
                color = "red1";
                break;
            case "Drk Red":
                color = "darkred";
                break;
            case "Yellow":
                color = "yellow";
                break;
            case "Drk Yellow":
                color = "yellow3";
                break;
            case "Lgt Green":
                color = "green1";
                break;
            case "Green":
                color = "green";
                break;
            case "Drk Green":
                color = "green4";
                break;
            case "Orange":
                color = "orange2";
                break;
            case "Brown":
                color = "brown";
                break;
            case "Purple":
                color = "purple";
                break;
            case "Lgt Grey":
                color = "grey60";
                break;
            case "Med Grey":
                color = "grey45";
                break;
            case "Drk Grey":
                color = "grey25";
                break;
            case "Black":
                color = "black";
                break;
        }
        return color;
    }
    private String symbolFormat(String str) {
        String symbol = "";
        System.out.println(str);
        switch(str) {
            case "Circle":
                symbol = "16";
                break;
            case "Triangle":
                symbol = "17";
                break;
            case "Square":
                symbol = "15";
                break;
            case "Diamond":
                symbol = "18";
                break;
            case "Star":
                symbol = "11";
                break;
            case "Burst":
                symbol = "8";
                break;
            case "X":
                symbol = "4";
                break;
            default:
                System.out.println("error");
                symbol = "0";
        }
        return symbol;
    }
    
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox averageStatsCheckBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel color1Label;
    private javax.swing.JLabel color2Label;
    private javax.swing.JLabel color3Label;
    private javax.swing.JLabel color4Label;
    private javax.swing.JLabel color5Label;
    private javax.swing.JPanel color6Label;
    private javax.swing.JPanel color7Label;
    private javax.swing.JLabel color8Label;
    private javax.swing.JComboBox<String> colorComboBox1;
    private javax.swing.JComboBox<String> colorComboBox10;
    private javax.swing.JComboBox<String> colorComboBox11;
    private javax.swing.JComboBox<String> colorComboBox12;
    private javax.swing.JComboBox<String> colorComboBox13;
    private javax.swing.JComboBox<String> colorComboBox14;
    private javax.swing.JComboBox<String> colorComboBox15;
    private javax.swing.JComboBox<String> colorComboBox16;
    private javax.swing.JComboBox<String> colorComboBox2;
    private javax.swing.JComboBox<String> colorComboBox3;
    private javax.swing.JComboBox<String> colorComboBox4;
    private javax.swing.JComboBox<String> colorComboBox5;
    private javax.swing.JComboBox<String> colorComboBox6;
    private javax.swing.JComboBox<String> colorComboBox7;
    private javax.swing.JComboBox<String> colorComboBox8;
    private javax.swing.JComboBox<String> colorComboBox9;
    private javax.swing.JCheckBox confidenceLinesCheckBox;
    private javax.swing.JCheckBox correlationCheckBox;
    private javax.swing.JCheckBox errorCheckBox;
    private javax.swing.JCheckBox fractionalBiasCheckBox;
    private javax.swing.JCheckBox fractionalErrorCheckBox;
    private javax.swing.JCheckBox indexOfAgreementCheckBox;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JCheckBox meanBiasCheckBox;
    private javax.swing.JCheckBox meanErrorCheckBox;
    private javax.swing.JCheckBox meanModelCheckBox;
    private javax.swing.JCheckBox meanObsCheckBox;
    private javax.swing.JCheckBox medianBiasCheckBox;
    private javax.swing.JCheckBox medianErrorCheckBox;
    private javax.swing.JCheckBox modelValuesCheckBox;
    private javax.swing.JLabel network1Label;
    private javax.swing.JLabel network2Label;
    private javax.swing.JLabel network3Label;
    private javax.swing.JLabel network4Label;
    private javax.swing.JLabel network5Label;
    private javax.swing.JLabel network6Label;
    private javax.swing.JLabel network7Label;
    private javax.swing.JCheckBox normMeanBiasCheckBox;
    private javax.swing.JCheckBox normMeanErrorCheckBox;
    private javax.swing.JCheckBox normMedianBiasCheckBox;
    private javax.swing.JCheckBox normMedianErrorCheckBox;
    private javax.swing.JCheckBox numberOfPairsCheckBox;
    private javax.swing.JCheckBox pcaRegionsCheckBox;
    private javax.swing.JLabel plotColorLabel;
    private javax.swing.JPanel plotColorPanel;
    private javax.swing.JPanel plotOptionsPanel;
    private javax.swing.JPanel plotSymbolpanel;
    private javax.swing.JLabel plotSymbolsLabel;
    private javax.swing.JCheckBox rSquaredCheckBox;
    private javax.swing.JCheckBox rmseCheckBox;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel scatterPlotOptionsLabel;
    private javax.swing.JLabel statisticsLabel;
    private javax.swing.JPanel statisticsPanel;
    private javax.swing.JComboBox<String> symbolComboBox1;
    private javax.swing.JComboBox<String> symbolComboBox2;
    private javax.swing.JComboBox<String> symbolComboBox3;
    private javax.swing.JComboBox<String> symbolComboBox4;
    private javax.swing.JComboBox<String> symbolComboBox5;
    private javax.swing.JComboBox<String> symbolComboBox6;
    private javax.swing.JComboBox<String> symbolComboBox7;
    private javax.swing.JCheckBox systematicRMSECheckBox;
    private javax.swing.JCheckBox trendLineCheckBox;
    private javax.swing.JCheckBox unsysematicRMSECheckBox;
    // End of variables declaration//GEN-END:variables
}
